# Указываем директорию, где будем хранить файлы (путь указывается относительно корня)
file:
  directory: files

spring:
  h2.console.enabled: true
  liquibase:
    enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/cars
    username: postgres
    password: Okhorzina2912
  servlet:
    multipart:
      # Указываем максимальный размер файла (по умолчанию 1MB, что неудобно, т.к. некоторые изображения могут весить много)
      max-file-size: 10MB